Developemnt
thankgodr/Todolist---Webpack pull request #1
Opened 2022-11-01 22:47 UTC by thankgodr

## This PR contains 

-  Setup for the Todo app
-  Webpack in configuration
-  HtmlWebpackPlugin
- CSS loader and styloader
- Lint code
- Requirements for To Do list: list structure

2022-11-01 23:56 UTC, ElsonOtake requested changes
STATUS: CHANGES REQUIRED 🟡 

Hi @thankgodr,

Good job so far! 🎉 🎉 
There are some issues that you still need to work on to go to the next project but you are almost there! 🥲 🥲 

![woohoo-youre-almost](https://user-images.githubusercontent.com/77038610/154921145-1f7bb8f6-c843-4ba5-a534-6b840c600558.jpeg)

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 23:56 UTC, ElsonOtake commented on src/js/index.js
> +    taskManager.addTask(singleTask2);
- I think it's better to create an array of objects (description, completed, and index). It's a project requirement.

2022-11-02 10:54 UTC, thankgodr commented on src/js/index.js
> +    taskManager.addTask(singleTask2);
@ElsonOtake the object is the taskmanager class. I just use the addtask method to add a single task to the array containing the objects (Task).

2022-11-02 13:56 UTC, ahmetbozaci reviewed
### Hello @thankgodr 
### _This is an additional review as a result of the second opinion request._ 




- [ ] [Requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md#:~:text=Create%20an%20index.js,index%3A%20%5Bnumber%5D.) are clear please follow the requirements


_![1](https://media.giphy.com/media/xT5LMScZteTtJ1j5q8/giphy.gif)
__



### Cheers and Happy coding! 💻 👏
____
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-11-02 16:40 UTC, t-yanick approved these changes
Hi @thankgodr, 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 21:59 UTC, merged